/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.gamemenubuilder;


/**
  WARNING: This type is defined as NoExport by UHT. It will be empty because of it
  
  
**/
@:umodule("GameMenuBuilder")
@:glueCppIncludes("GameMenuWidgetStyle.h")
@:noCopy @:noEquals @:uextern extern class FGameMenuStyle extends unreal.slatecore.FSlateWidgetStyle {
  
  /**
    Color of the text.
  **/
  public var TextColor : unreal.slatecore.FSlateColor;
  
  /**
    Speed at which the menu initially appears.
  **/
  public var AnimationSpeed : unreal.Float32;
  
  /**
    Panel vertical alignment.
  **/
  public var PanelsVerticalAlignment : unreal.slatecore.EVerticalAlignment;
  
  /**
    Title vertical alignment.
  **/
  public var TitleVerticalAlignment : unreal.slatecore.EVerticalAlignment;
  
  /**
    Title horizontal alignment.
  **/
  public var TitleHorizontalAlignment : unreal.slatecore.EHorizontalAlignment;
  
  /**
    Item border margin.
  **/
  public var ItemBorderMargin : unreal.slatecore.FMargin;
  
  /**
    Title border margin.
  **/
  public var TitleBorderMargin : unreal.slatecore.FMargin;
  
  /**
    Layout type.
  **/
  public var LayoutType : unreal.gamemenubuilder.GameMenuLayoutType;
  
  /**
    The left hand margin for the sub menu
  **/
  public var SubMenuMarginPercent : unreal.Float32;
  
  /**
    The left hand margin for the main menu
  **/
  public var LeftMarginPercent : unreal.Float32;
  
  /**
    The sound the menu should play when the selected menu item is chosen
  **/
  public var MenuItemChosenSound : unreal.slatecore.FSlateSound;
  
  /**
    The sound the menu should play when the selected menu item is disabled or unbound
  **/
  public var MenuItemInactiveSound : unreal.slatecore.FSlateSound;
  
  /**
    The sound the menu should play when the selected menu item is changed
  **/
  public var MenuItemChangeSound : unreal.slatecore.FSlateSound;
  
  /**
    The sound the menu should play when a menu option is changed
  **/
  public var OptionChangeSound : unreal.slatecore.FSlateSound;
  
  /**
    The sound the menu should play when returning to a parent menu
  **/
  public var MenuBackSound : unreal.slatecore.FSlateSound;
  
  /**
    The sound the menu should play when entering a sub-menu
  **/
  public var MenuEnterSound : unreal.slatecore.FSlateSound;
  
  /**
    The brush used to draw the selected menu item
  **/
  public var MenuSelectBrush : unreal.slatecore.FSlateBrush;
  
  /**
    The brush used to draw the menu background
  **/
  public var MenuBackgroundBrush : unreal.slatecore.FSlateBrush;
  
  /**
    The brush used to draw the menu border
  **/
  public var MenuFrameBrush : unreal.slatecore.FSlateBrush;
  
  /**
    The brush used to draw the top of the menu
  **/
  public var MenuTopBrush : unreal.slatecore.FSlateBrush;
  
}
