/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.gamemenubuilder;

@:umodule("GameMenuBuilder")
@:glueCppIncludes("GameMenuWidgetStyle.h")
@:uname("GameMenuLayoutType.Type")
@:uextern extern enum GameMenuLayoutType {
  
  /**
    Single one page menu.
  **/
  Single;
  
  /**
    Side by side menu. Main menu on left, any sub menu on right.
  **/
  SideBySide;
  
}
